#
### dnsutils
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsutils
  labels:
    app: dnsutils
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: dnsutils
  template:
    metadata:
      labels:
        app: dnsutils
    spec:
      containers:
      - name: dnsutils
        image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
        command:
          - sleep
          - "3600"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
