# This is the service account that the sidecar requires in order to query the API server for
# any new release upgrades resources
apiVersion: v1
kind: ServiceAccount
metadata:
 name: erlang-relup-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-release-upgrades
rules:
- apiGroups:
  - relup.lrascao.github.io
  resources:
  - releaseupgrades
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: read-release-upgrades_erlang-relup-service-account
    namespace: default
roleRef:
    kind: ClusterRole
    name: read-release-upgrades
    apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: erlang-relup-service-account
    namespace: default
