apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-web-service
  region: eu-central-1

vpc:
  subnets:
    private:
      # subnets below should be public, otherwise your load balances won't
      # be able to created without using tags as described in:
      #   https://github.com/kubernetes/kubernetes/issues/29298#issuecomment-274400650
      eu-central-1a: { id: subnet-db113cb0 }
      eu-central-1b: { id: subnet-f3019a8e }
      eu-central-1c: { id: subnet-827b0dcf }

nodeGroups:
  - name: ng-1-workers
    labels: {
      role: workers
    }
    instanceType: t2.small
    desiredCapacity: 1
    privateNetworking: true
