#!/bin/bash

# Replace environment variables
replace_os_vars() {
    basename=$(basename $1)
    cp $1 /tmp/$basename.orig
    awk '{
        while(match($0,"[$]{[^}]*}")) {
            var=substr($0,RSTART+2,RLENGTH -3)
            gsub("[$]{"var"}",ENVIRON[var])
        }
    }1' < "/tmp/$basename.orig" > "$1"
}

# we'll do a massive find/replace over all of the configuration
# files
# start with sys.config
replace_os_vars "releases/$REL_VSN/sys.config"
# and go through all .config files in config/ dir
for ConfigFile in releases/$REL_VSN/config/*.config; do
    replace_os_vars $ConfigFile
done

